### ISSUE TITLE
bricolage-jobnet --help does not work

### ISSUE THREAD

**Issue by aamine** [aamine/bricolage#23]
```
% be bricolage-jobnet --help
.../bundle/ruby/2.1.0/gems/bricolage-5.9.3/lib/bricolage/jobnetrunner.rb:240:in `block in define_options': private method `puts' called for #<Bricolage::JobNetRunner:0x000000024b5f30> (NoMethodError)
        from /usr/lib64/ruby/2.1.0/optparse.rb:1359:in `call'
        from /usr/lib64/ruby/2.1.0/optparse.rb:1359:in `block in parse_in_order'
        from /usr/lib64/ruby/2.1.0/optparse.rb:1346:in `catch'
        from /usr/lib64/ruby/2.1.0/optparse.rb:1346:in `parse_in_order'
        from /usr/lib64/ruby/2.1.0/optparse.rb:1340:in `order!'
        from /usr/lib64/ruby/2.1.0/optparse.rb:1432:in `permute!'
        from /usr/lib64/ruby/2.1.0/optparse.rb:1454:in `parse!'
        from .../bundle/ruby/2.1.0/gems/bricolage-5.9.3/lib/bricolage/jobnetrunner.rb:254:in `parse'
        from .../bundle/ruby/2.1.0/gems/bricolage-5.9.3/lib/bricolage/jobnetrunner.rb:38:in `main'
        from .../bundle/ruby/2.1.0/gems/bricolage-5.9.3/lib/bricolage/jobnetrunner.rb:20:in `main'
        from .../bundle/ruby/2.1.0/gems/bricolage-5.9.3/bin/bricolage-jobnet:6:in `<top (required)>'
        from .../bundle/ruby/2.1.0/bin/bricolage-jobnet:23:in `load'
        from .../bundle/ruby/2.1.0/bin/bricolage-jobnet:23:in `<main>'
```

**Comment by aamine** [comment]
fixed in 5.11.1 or later
